# Welcome to Jekyll!
#

# Site settings
title: Raghav Prasad
description: |
  "--- Never Settle ---"
owner: Raghav Prasad # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: raghavprasad13@gmail.com
baseurl: "/site" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  email: mailto:raghavprasad13@gmail.com
  github: https://github.com/raghavprasad13
  linkedin-square: https://www.linkedin.com/in/raghav-prasad-857383166/
  facebook-official: https://www.facebook.com/raghavprasad131297?ref=bookmarks
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
